In [3]:
import numpy as np

In [4]:
# Data structure: [restaurant_id, 2020, 2022, 2023, 2024]
sales_data = np.array([
[1, 150000, 180000, 220000, 250000], # Paradise Biryani
[2, 120000, 140000, 160000, 190000], # Beijing Bites
[3, 200000, 230000, 260000, 300000], # Pizza Hub
[4, 180000, 210000, 240000, 270000], # Burger Point
[5, 160000, 185000, 205000, 230000] # Chai Point
])

## Accessing the Data

In [12]:
print("-----Swiggy Sales Analysis------")
print("Shape of data" , sales_data.shape)
print("First Third Row of Sales Data: \n", sales_data[:4,:])
print("-----------------------------------------------------")
print("Only Sales from Sales Data: \n", sales_data[:,1:])


-----Swiggy Sales Analysis------
Shape of data (5, 5)
First Third Row of Sales Data: 
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]]
-----------------------------------------------------
Only Sales from Sales Data: 
 [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


## Calculation

In [ ]:
print(sales_data)
print("Total Sales per Restaurent: ",np.sum(sales_data[:,1:],axis=1))
print("Total Sales per Year: ",np.sum(sales_data[:,1:],axis=0))
print("Maximum Sales per Restaurent: ",np.max(sales_data[:,1:],axis=1))
print("Minimum Sales per Year: ",np.min(sales_data[:,1:],axis=0))
print("Average Sales per Restaurent: ",np.mean(sales_data[:,1:],axis=1))

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
Total Sales per Restaurent:  [800000 610000 990000 900000 780000]
Total Sales per Year:  [ 810000  945000 1085000 1240000]
Maximum Sales per Restaurent:  [250000 190000 300000 270000 230000]
Minimum Sales per Year:  [120000 140000 160000 190000]
Average Sales per Restaurent:  [200000. 152500. 247500. 225000. 195000.]
